import { auditEvent } from "@/lib/audit";
import { authenticatedUser, getUser, hasPermission, listUsers, updateUser } from "@/lib/auth";
import { roles, type Role } from "@/lib/auth-types";
import { apiError, apiHeaders } from "@/lib/observability";
import { limitedJson, sameOrigin } from "@/lib/verification-auth";
import { verificationStore } from "@/lib/verification-store";
export const runtime = "nodejs";
const mayManage = (role: Role, target: Role) => role === "SUPER_ADMIN" || (role === "ADMIN" && !["SUPER_ADMIN", "ADMIN"].includes(target));
export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }) { if (!sameOrigin(request)) return apiError("FORBIDDEN", 403, request); try { const store = verificationStore(); const actor = await authenticatedUser(store, request); if (!actor) return apiError("UNAUTHORIZED", 401, request); if (!hasPermission(actor.role, "users.update")) return apiError("FORBIDDEN", 403, request); const { id } = await context.params; const target = await getUser(store, id); if (!target) return apiError("NOT_FOUND", 404, request); const body = await limitedJson(request) as { displayName?: unknown; role?: unknown; status?: unknown }; const nextRole = body.role === undefined ? target.role : body.role as Role; const nextStatus = body.status === undefined ? target.status : body.status as "ACTIVE" | "DISABLED"; if (!roles.includes(nextRole) || !["ACTIVE", "DISABLED"].includes(nextStatus) || !mayManage(actor.role, target.role) || !mayManage(actor.role, nextRole)) return apiError("FORBIDDEN", 403, request); if (target.role === "SUPER_ADMIN" && (nextRole !== "SUPER_ADMIN" || nextStatus === "DISABLED") && (await listUsers(store)).filter((user) => user.role === "SUPER_ADMIN" && user.status === "ACTIVE").length <= 1) return apiError("CONFLICT", 409, request); const user = await updateUser(store, id, { ...(typeof body.displayName === "string" ? { displayName: body.displayName } : {}), role: nextRole, status: nextStatus }); if (!user) return apiError("NOT_FOUND", 404, request); await store.appendAudit(auditEvent({ action: nextStatus === "DISABLED" ? "auth.user.disabled" : "auth.user.updated", entityType: "user", entityReference: user.id, result: "success", context: { role: user.role } })); return Response.json({ user }, { headers: apiHeaders(request) }); } catch { return apiError("DEPENDENCY_UNAVAILABLE", 503, request); } }
