import type { Language } from "./i18n";

const en = {
  "plan.title":"2D plan", "plan.previewDescription":"Open the complete editable 2D plan when you are ready to inspect it.", "plan.open":"Open 2D plan", "plan.back":"Back to calculator", "plan.select":"Select", "plan.measure":"Measure", "plan.grid":"Grid", "plan.snap":"Snap", "plan.dimensions":"Dimensions", "plan.labels":"Labels", "plan.zoomIn":"Zoom in", "plan.zoomOut":"Zoom out", "plan.fit":"Fit to view", "plan.reset":"Reset view", "plan.fullscreen":"Fullscreen", "plan.exitFullscreen":"Exit fullscreen", "plan.properties":"Properties", "plan.distance":"Distance", "plan.readOnly":"Read only", "plan.export":"Export SVG", "plan.print":"Print plan", "plan.noGeometry":"Enter valid room or wall dimensions to draw the plan.", "plan.notToScale":"Not to scale", "plan.validation":"Validation", "plan.selection":"Selection", "plan.opening":"Opening", "plan.room":"Room", "plan.wall":"Wall", "plan.door":"Door", "plan.window":"Window"
};
const ku = {
  "plan.title":"پلانێکی ٢D", "plan.previewDescription":"کاتێک ئامادەیت پلانە تەواوە دەستکاریکراوەکەی ٢D بکەرەوە.", "plan.open":"کردنەوەی پلانی ٢D", "plan.back":"گەڕانەوە بۆ حیسابکەر", "plan.select":"هەڵبژاردن", "plan.measure":"پێوانە", "plan.grid":"تۆڕ", "plan.snap":"چسپاندن", "plan.dimensions":"ڕەهەندەکان", "plan.labels":"ناونیشانەکان", "plan.zoomIn":"گەورەکردن", "plan.zoomOut":"بچووککردن", "plan.fit":"گونجاندن بۆ بینین", "plan.reset":"ڕێکخستنەوەی بینین", "plan.fullscreen":"شاشەی تەواو", "plan.exitFullscreen":"دەرچوون لە شاشەی تەواو", "plan.properties":"تایبەتمەندییەکان", "plan.distance":"دووری", "plan.readOnly":"تەنها خوێندنەوە", "plan.export":"هەناردەی SVG", "plan.print":"چاپی پلان", "plan.noGeometry":"ڕەهەندی دروستی ژوور یان دیوار بنووسە بۆ کێشانی پلان.", "plan.notToScale":"نەک بەپێی پێوەری چاپ", "plan.validation":"پشکنین", "plan.selection":"هەڵبژاردن", "plan.opening":"کراوە", "plan.room":"ژوور", "plan.wall":"دیوار", "plan.door":"دەرگا", "plan.window":"پەنجەرە"
};
const ar = {
  "plan.title":"المخطط ثنائي الأبعاد", "plan.previewDescription":"افتح المخطط ثنائي الأبعاد الكامل القابل للتحرير عند الحاجة إلى معاينته.", "plan.open":"فتح المخطط ثنائي الأبعاد", "plan.back":"العودة إلى الحاسبة", "plan.select":"تحديد", "plan.measure":"قياس", "plan.grid":"شبكة", "plan.snap":"التقاط", "plan.dimensions":"الأبعاد", "plan.labels":"التسميات", "plan.zoomIn":"تكبير", "plan.zoomOut":"تصغير", "plan.fit":"ملاءمة للعرض", "plan.reset":"إعادة ضبط العرض", "plan.fullscreen":"ملء الشاشة", "plan.exitFullscreen":"خروج من ملء الشاشة", "plan.properties":"الخصائص", "plan.distance":"المسافة", "plan.readOnly":"للقراءة فقط", "plan.export":"تصدير SVG", "plan.print":"طباعة المخطط", "plan.noGeometry":"أدخل أبعاد غرفة أو جدار صالحة لرسم المخطط.", "plan.notToScale":"ليس بمقياس طباعة", "plan.validation":"التحقق", "plan.selection":"التحديد", "plan.opening":"فتحة", "plan.room":"غرفة", "plan.wall":"جدار", "plan.door":"باب", "plan.window":"نافذة"
};

export const phase14Messages: Record<Language, Record<keyof typeof en, string>> = { "en-GB": en, ku, ar };
