import type { Language } from "./i18n";

const en = {
  "auth.createAccount": "Create account", "auth.username": "Username", "auth.confirmPassword": "Confirm password", "auth.passwordMatch": "Passwords must match.", "auth.passwordStrength": "Password strength", "auth.weak": "Weak", "auth.medium": "Medium", "auth.strong": "Strong", "auth.veryStrong": "Very strong", "auth.accountCreated": "Account created. Check your email to verify it before signing in.", "auth.verificationRequired": "Verify your email before signing in.", "auth.forgotPassword": "Forgot password?", "auth.resetSent": "If an account exists, a reset link has been sent.", "auth.identifier": "Email or username", "auth.verifySuccess": "Your email has been verified. You can now sign in.",
  "auth.passwordRequirements": "Password requirements", "auth.passwordMinLength": "At least 12 characters", "auth.passwordLowercase": "At least one lowercase letter (a-z)", "auth.passwordUppercase": "At least one uppercase letter (A-Z)", "auth.passwordDigit": "At least one number (0-9)", "auth.passwordSymbol": "At least one special character (!@#$...)", "auth.passwordClasses": "Use at least 3 of these 4 character types, or use 20 or more characters.", "auth.passwordTooLong": "Use no more than 1024 characters.", "auth.passwordInvalid": "Your password does not yet meet all requirements.", "auth.passwordsMatch": "Passwords match.", "auth.usernameInvalid": "Use 3–30 letters, numbers, dots, underscores or hyphens; it cannot be reserved.", "auth.emailInvalid": "Enter a valid email address.", "auth.displayNameInvalid": "Enter a display name of up to 120 characters.", "auth.emailTaken": "This email address is already registered.", "auth.usernameTaken": "This username is already in use.", "auth.emailUnavailable": "We could not send the verification email. Please try again later.", "auth.rateLimited": "Please wait a few minutes before trying again.", "auth.signupUnavailable": "Registration is temporarily unavailable. Please try again later.", "auth.fixForm": "Please correct the highlighted fields.",
} as const;
type Key = keyof typeof en;

export const phase17Messages: Record<Language, Record<Key, string>> = {
  "en-GB": en,
  ku: {
    "auth.createAccount":"دروستکردنی هەژمار", "auth.username":"ناوی بەکارهێنەر", "auth.confirmPassword":"دووپاتکردنەوەی وشەی نهێنی", "auth.passwordMatch":"وشە نهێنییەکان یەکسان نین.", "auth.passwordStrength":"بەهێزی وشەی نهێنی", "auth.weak":"لاواز", "auth.medium":"مامناوەند", "auth.strong":"بەهێز", "auth.veryStrong":"زۆر بەهێز", "auth.accountCreated":"هەژمار دروستکرا. ئیمەیڵەکەت بپشکنە بۆ پشتڕاستکردنەوە پێش چوونەژوورەوە.", "auth.verificationRequired":"پێش چوونەژوورەوە ئیمەیڵەکەت پشتڕاست بکەوە.", "auth.forgotPassword":"وشەی نهێنیت لەبیرچووە؟", "auth.resetSent":"ئەگەر هەژمارێک هەبێت، بەستەری ڕێکخستنەوە نێردراوە.", "auth.identifier":"ئیمەیڵ یان ناوی بەکارهێنەر", "auth.verifySuccess":"ئیمەیڵەکەت پشتڕاستکرایەوە. ئێستا دەتوانیت بچیتە ژوورەوە.",
    "auth.passwordRequirements":"مەرجەکانی وشەی نهێنی", "auth.passwordMinLength":"لانیکەم ١٢ پیت", "auth.passwordLowercase":"لانیکەم یەک پیتی بچووک (a-z)", "auth.passwordUppercase":"لانیکەم یەک پیتی گەورە (A-Z)", "auth.passwordDigit":"لانیکەم یەک ژمارە (0-9)", "auth.passwordSymbol":"لانیکەم یەک هێمای تایبەت (!@#$...)", "auth.passwordClasses":"لەو چوار جۆرەدا لانیکەم سێ جۆر بەکاربهێنە، یان ٢٠ پیت یان زیاتر.", "auth.passwordTooLong":"تکایە زیاتر لە ١٠٢٤ پیت بەکارمەهێنە.", "auth.passwordInvalid":"وشەی نهێنییەکەت هێشتا هەموو مەرجەکان پڕ ناکاتەوە.", "auth.passwordsMatch":"وشە نهێنییەکان یەکسانن.", "auth.usernameInvalid":"٣ تا ٣٠ پیت، ژمارە، خاڵ، ژێرهێڵ یان هێمای کەمەند بەکاربهێنە؛ ناوی قەدەغەکراو مەبێت.", "auth.emailInvalid":"تکایە ناونیشانی ئیمەیڵێکی دروست بنووسە.", "auth.displayNameInvalid":"ناوی پیشاندان بنووسە؛ نابێت لە ١٢٠ پیت زیاتر بێت.", "auth.emailTaken":"ئەم ناونیشانی ئیمەیڵە پێشتر تۆمارکراوە.", "auth.usernameTaken":"ئەم ناوی بەکارهێنەرە پێشتر بەکارهاتووە.", "auth.emailUnavailable":"نەتوانرا ئیمەیڵی پشتڕاستکردنەوە بنێردرێت. تکایە دواتر هەوڵ بدەوە.", "auth.rateLimited":"تکایە چەند خولەکێک چاوەڕێ بکە پێش هەوڵدانەوە.", "auth.signupUnavailable":"تۆمارکردن کاتێک بەردەست نییە. تکایە دواتر هەوڵ بدەوە.", "auth.fixForm":"تکایە خانە نیشانکراوەکان چاک بکەوە.",
  },
  ar: {
    "auth.createAccount":"إنشاء حساب", "auth.username":"اسم المستخدم", "auth.confirmPassword":"تأكيد كلمة المرور", "auth.passwordMatch":"كلمتا المرور غير متطابقتين.", "auth.passwordStrength":"قوة كلمة المرور", "auth.weak":"ضعيفة", "auth.medium":"متوسطة", "auth.strong":"قوية", "auth.veryStrong":"قوية جداً", "auth.accountCreated":"تم إنشاء الحساب. تحقق من بريدك الإلكتروني قبل تسجيل الدخول.", "auth.verificationRequired":"تحقق من بريدك الإلكتروني قبل تسجيل الدخول.", "auth.forgotPassword":"هل نسيت كلمة المرور؟", "auth.resetSent":"إذا كان الحساب موجوداً، فقد أُرسل رابط إعادة التعيين.", "auth.identifier":"البريد الإلكتروني أو اسم المستخدم", "auth.verifySuccess":"تم التحقق من بريدك الإلكتروني. يمكنك الآن تسجيل الدخول.",
    "auth.passwordRequirements":"متطلبات كلمة المرور", "auth.passwordMinLength":"12 حرفاً على الأقل", "auth.passwordLowercase":"حرف صغير واحد على الأقل (a-z)", "auth.passwordUppercase":"حرف كبير واحد على الأقل (A-Z)", "auth.passwordDigit":"رقم واحد على الأقل (0-9)", "auth.passwordSymbol":"رمز خاص واحد على الأقل (!@#$...)", "auth.passwordClasses":"استخدم 3 أنواع على الأقل من هذه الأنواع الأربعة، أو استخدم 20 حرفاً أو أكثر.", "auth.passwordTooLong":"لا تستخدم أكثر من 1024 حرفاً.", "auth.passwordInvalid":"كلمة المرور لا تستوفي جميع المتطلبات بعد.", "auth.passwordsMatch":"كلمتا المرور متطابقتان.", "auth.usernameInvalid":"استخدم 3–30 حرفاً أو رقماً أو نقطة أو شرطة سفلية أو واصلة؛ ولا يمكن أن يكون الاسم محجوزاً.", "auth.emailInvalid":"أدخل عنوان بريد إلكتروني صالحاً.", "auth.displayNameInvalid":"أدخل اسماً معروضاً لا يزيد عن 120 حرفاً.", "auth.emailTaken":"عنوان البريد الإلكتروني هذا مسجل بالفعل.", "auth.usernameTaken":"اسم المستخدم هذا مستخدم بالفعل.", "auth.emailUnavailable":"تعذر إرسال رسالة التحقق. يرجى المحاولة لاحقاً.", "auth.rateLimited":"يرجى الانتظار بضع دقائق قبل المحاولة مرة أخرى.", "auth.signupUnavailable":"التسجيل غير متاح مؤقتاً. يرجى المحاولة لاحقاً.", "auth.fixForm":"يرجى تصحيح الحقول المميزة.",
  },
};
