import type { Language } from "@/lib/i18n";

type Messages = Record<"project.number" | "project.client" | "project.description" | "project.status" | "project.measurement" | "project.metric" | "project.imperial" | "project.draft" | "project.active" | "project.completed" | "project.archived" | "rooms.duplicate" | "rooms.moveUp" | "rooms.moveDown" | "options.waste3" | "options.waste7", string>;

export const phase3Messages: Record<Language, Messages> = {
  "en-GB": { "project.number": "Project reference", "project.client": "Client", "project.description": "Description", "project.status": "Project status", "project.measurement": "Measurement system", "project.metric": "Metric (m, cm, mm)", "project.imperial": "Imperial (ft, in)", "project.draft": "Draft", "project.active": "Active", "project.completed": "Completed", "project.archived": "Archived", "rooms.duplicate": "Duplicate room", "rooms.moveUp": "Move room up", "rooms.moveDown": "Move room down", "options.waste3": "3%", "options.waste7": "7%" },
  ku: { "project.number": "ژمارەی پڕۆژە", "project.client": "کڕیار", "project.description": "وەسف", "project.status": "دۆخی پڕۆژە", "project.measurement": "سیستەمی پێوانە", "project.metric": "مەترێک (م، سم، ملم)", "project.imperial": "ئیمپریاڵ (پێ، ئینچ)", "project.draft": "تەواونەکراو", "project.active": "چالاک", "project.completed": "تەواوکراو", "project.archived": "ئەرشیفکراو", "rooms.duplicate": "کۆپیکردنی ژوور", "rooms.moveUp": "بردنە سەرەوە", "rooms.moveDown": "بردنە خوارەوە", "options.waste3": "٣٪", "options.waste7": "٧٪" },
  ar: { "project.number": "مرجع المشروع", "project.client": "العميل", "project.description": "الوصف", "project.status": "حالة المشروع", "project.measurement": "نظام القياس", "project.metric": "متري (م، سم، ملم)", "project.imperial": "إمبراطوري (قدم، بوصة)", "project.draft": "مسودة", "project.active": "نشط", "project.completed": "مكتمل", "project.archived": "مؤرشف", "rooms.duplicate": "نسخ الغرفة", "rooms.moveUp": "نقل الغرفة لأعلى", "rooms.moveDown": "نقل الغرفة لأسفل", "options.waste3": "٣٪", "options.waste7": "٧٪" },
};
