import type { Language } from "@/lib/i18n";

type Messages = Record<
  | "scenario.title" | "scenario.description" | "scenario.add" | "scenario.empty" | "scenario.createFirst"
  | "scenario.name" | "scenario.block" | "scenario.waste" | "scenario.price" | "scenario.currency"
  | "scenario.duplicate" | "scenario.delete" | "scenario.deleteConfirm" | "scenario.reset" | "scenario.baseline"
  | "scenario.active" | "scenario.notes" | "scenario.difference" | "scenario.noComparableCurrency"
  | "scenario.gross" | "scenario.openings" | "scenario.net" | "scenario.base" | "scenario.wasteBlocks"
  | "scenario.final" | "scenario.material" | "scenario.labour" | "scenario.transport" | "scenario.additional"
  | "scenario.total" | "scenario.invalid" | "scenario.scope" | "scenario.report" | "scenario.reportReady", string>;

export const scenarioMessages: Record<Language, Messages> = {
  "en-GB": {
    "scenario.title": "Scenario comparison", "scenario.description": "Compare material and cost choices against the same project geometry.", "scenario.add": "Add scenario", "scenario.empty": "Create scenarios to compare block specifications, waste and cost using this project’s current geometry.", "scenario.createFirst": "Create first scenario", "scenario.name": "Scenario name", "scenario.block": "Block type", "scenario.waste": "Waste (%)", "scenario.price": "Unit price", "scenario.currency": "Currency", "scenario.duplicate": "Duplicate", "scenario.delete": "Delete", "scenario.deleteConfirm": "Delete this scenario?", "scenario.reset": "Reset to project settings", "scenario.baseline": "Baseline", "scenario.active": "Active scenario", "scenario.notes": "Notes", "scenario.difference": "Difference", "scenario.noComparableCurrency": "Money differences need matching currencies.", "scenario.gross": "Gross area", "scenario.openings": "Openings", "scenario.net": "Net area", "scenario.base": "Base quantity", "scenario.wasteBlocks": "Waste quantity", "scenario.final": "Final quantity", "scenario.material": "Material cost", "scenario.labour": "Labour", "scenario.transport": "Transport", "scenario.additional": "Additional costs", "scenario.total": "Grand total", "scenario.invalid": "This scenario has incomplete or invalid inputs.", "scenario.scope": "Current project geometry", "scenario.report": "Comparison report", "scenario.reportReady": "Comparison report downloaded."
  },
  ku: {
    "scenario.title": "بەراوردی دۆخەکان", "scenario.description": "هەڵبژاردەکانی کەرەستە و تێچوو بە هەمان ئەندازەی پڕۆژە بەراورد بکە.", "scenario.add": "زیادکردنی دۆخ", "scenario.empty": "دۆخ دروست بکە بۆ بەراوردی بلۆک، زیادە و تێچوو بە ئەندازەی ئێستای پڕۆژە.", "scenario.createFirst": "یەکەم دۆخ دروست بکە", "scenario.name": "ناوی دۆخ", "scenario.block": "جۆری بلۆک", "scenario.waste": "زیادە (%)", "scenario.price": "نرخی یەک بلۆک", "scenario.currency": "دراو", "scenario.duplicate": "دووبارەکردنەوە", "scenario.delete": "سڕینەوە", "scenario.deleteConfirm": "ئەم دۆخە بسڕدرێتەوە؟", "scenario.reset": "گەڕاندنەوە بۆ ڕێکخستنەکانی پڕۆژە", "scenario.baseline": "بنەما", "scenario.active": "دۆخی چالاک", "scenario.notes": "تێبینی", "scenario.difference": "جیاوازی", "scenario.noComparableCurrency": "جیاوازی پارە پێویستی بە هەمان دراو هەیە.", "scenario.gross": "ڕووبەری گشتی", "scenario.openings": "کراوەکان", "scenario.net": "ڕووبەری پاک", "scenario.base": "بڕی بنەڕەت", "scenario.wasteBlocks": "بڕی زیادە", "scenario.final": "بڕی کۆتایی", "scenario.material": "تێچووی کەرەستە", "scenario.labour": "کرێی کار", "scenario.transport": "گواستنەوە", "scenario.additional": "تێچووی زیادە", "scenario.total": "کۆی گشتی", "scenario.invalid": "زانیارییەکانی ئەم دۆخە ناتەواون یان نادروستن.", "scenario.scope": "ئەندازەی ئێستای پڕۆژە", "scenario.report": "ڕاپۆرتی بەراورد", "scenario.reportReady": "ڕاپۆرتی بەراورد دابەزێنرا."
  },
  ar: {
    "scenario.title": "مقارنة السيناريوهات", "scenario.description": "قارن خيارات المواد والتكلفة باستخدام هندسة المشروع نفسها.", "scenario.add": "إضافة سيناريو", "scenario.empty": "أنشئ سيناريوهات لمقارنة مواصفات البلوك والهدر والتكلفة باستخدام هندسة المشروع الحالية.", "scenario.createFirst": "إنشاء أول سيناريو", "scenario.name": "اسم السيناريو", "scenario.block": "نوع البلوك", "scenario.waste": "الهدر (%)", "scenario.price": "سعر الوحدة", "scenario.currency": "العملة", "scenario.duplicate": "نسخ", "scenario.delete": "حذف", "scenario.deleteConfirm": "حذف هذا السيناريو؟", "scenario.reset": "إعادة ضبط لإعدادات المشروع", "scenario.baseline": "خط الأساس", "scenario.active": "السيناريو النشط", "scenario.notes": "ملاحظات", "scenario.difference": "الفرق", "scenario.noComparableCurrency": "تتطلب فروقات المال عملات متطابقة.", "scenario.gross": "المساحة الإجمالية", "scenario.openings": "الفتحات", "scenario.net": "المساحة الصافية", "scenario.base": "الكمية الأساسية", "scenario.wasteBlocks": "كمية الهدر", "scenario.final": "الكمية النهائية", "scenario.material": "تكلفة المواد", "scenario.labour": "العمالة", "scenario.transport": "النقل", "scenario.additional": "تكاليف إضافية", "scenario.total": "الإجمالي", "scenario.invalid": "بيانات هذا السيناريو ناقصة أو غير صالحة.", "scenario.scope": "هندسة المشروع الحالية", "scenario.report": "تقرير المقارنة", "scenario.reportReady": "تم تنزيل تقرير المقارنة."
  },
};
