import type { Language } from "@/lib/i18n";

export const workspaceMessageKeys = [
  "workspace.heading", "workspace.description", "workspace.saved", "workspace.saving", "workspace.unsaved", "workspace.failed", "workspace.autosave", "workspace.manualSave", "workspace.newProject", "workspace.search", "workspace.favorites", "workspace.history", "workspace.notifications", "workspace.markAllRead", "workspace.noNotifications", "workspace.recentProjects", "workspace.recentActivity", "workspace.statistics", "workspace.projectsCount", "workspace.roomsCount", "workspace.wallsCount", "workspace.noFavorites", "workspace.addFavorite", "workspace.removeFavorite", "workspace.open", "workspace.restore", "workspace.restoreConfirm", "workspace.restoreSuccess", "workspace.historyEmpty", "workspace.revision", "workspace.autosaveVersion", "workspace.manualVersion", "workspace.restoreVersion", "workspace.searchPlaceholder", "workspace.searchEmpty", "workspace.searchNoResults", "workspace.recentSearches", "workspace.clearSearch", "workspace.openFavorites", "workspace.preferences", "workspace.customiseActions", "workspace.saveFailed", "workspace.saveSuccess", "workspace.discardConfirm", "workspace.keyboardHint", "workspace.close", "workspace.loading",
] as const;

type WorkspaceKey = (typeof workspaceMessageKeys)[number];
type WorkspaceMessages = Record<WorkspaceKey, string>;

export const workspaceMessages: Record<Language, WorkspaceMessages> = {
  "en-GB": {
    "workspace.heading": "Workspace", "workspace.description": "Your live project workspace", "workspace.saved": "Saved", "workspace.saving": "Saving…", "workspace.unsaved": "Unsaved changes", "workspace.failed": "Save failed", "workspace.autosave": "Autosave", "workspace.manualSave": "Save", "workspace.newProject": "New project", "workspace.search": "Search", "workspace.favorites": "Favorites", "workspace.history": "History", "workspace.notifications": "Notifications", "workspace.markAllRead": "Mark all as read", "workspace.noNotifications": "No notifications", "workspace.recentProjects": "Recent projects", "workspace.recentActivity": "Recent activity", "workspace.statistics": "Workspace statistics", "workspace.projectsCount": "Saved projects", "workspace.roomsCount": "Rooms", "workspace.wallsCount": "Walls", "workspace.noFavorites": "No favorites yet", "workspace.addFavorite": "Add to favorites", "workspace.removeFavorite": "Remove from favorites", "workspace.open": "Open", "workspace.restore": "Restore", "workspace.restoreConfirm": "Restore this version? A recovery version of the current project will be created first.", "workspace.restoreSuccess": "Version restored safely", "workspace.historyEmpty": "No saved versions yet", "workspace.revision": "Revision {value}", "workspace.autosaveVersion": "Autosave", "workspace.manualVersion": "Manual save", "workspace.restoreVersion": "Restored version", "workspace.searchPlaceholder": "Search projects, rooms, walls and saved records", "workspace.searchEmpty": "Start typing to search your workspace", "workspace.searchNoResults": "No matching workspace records", "workspace.recentSearches": "Recent searches", "workspace.clearSearch": "Clear", "workspace.openFavorites": "Open favorites", "workspace.preferences": "Workspace preferences", "workspace.customiseActions": "Choose quick actions", "workspace.saveFailed": "Your changes could not be saved. They remain open in this workspace.", "workspace.saveSuccess": "Project saved", "workspace.discardConfirm": "You have unsaved changes. Continue and discard them?", "workspace.keyboardHint": "Ctrl/Cmd + K", "workspace.close": "Close workspace panel", "workspace.loading": "Loading workspace…",
  },
  ku: {
    "workspace.heading": "شوێنی کار", "workspace.description": "شوێنی کارکردنی پڕۆژەی زیندووت", "workspace.saved": "پاشەکەوت کرا", "workspace.saving": "پاشەکەوت دەکرێت…", "workspace.unsaved": "گۆڕانکاری پاشەکەوت نەکراوە", "workspace.failed": "پاشەکەوتکردن سەرکەوتوو نەبوو", "workspace.autosave": "پاشەکەوتی خۆکار", "workspace.manualSave": "پاشەکەوتکردن", "workspace.newProject": "پڕۆژەی نوێ", "workspace.search": "گەڕان", "workspace.favorites": "دڵخوازەکان", "workspace.history": "مێژوو", "workspace.notifications": "ئاگادارییەکان", "workspace.markAllRead": "هەموویان بخوێنەوە", "workspace.noNotifications": "هیچ ئاگادارییەک نییە", "workspace.recentProjects": "پڕۆژە نوێیەکان", "workspace.recentActivity": "چالاکییە نوێیەکان", "workspace.statistics": "ئامارەکانی شوێنی کار", "workspace.projectsCount": "پڕۆژە پاشەکەوتکراوەکان", "workspace.roomsCount": "ژوورەکان", "workspace.wallsCount": "دیواره‌کان", "workspace.noFavorites": "هێشتا هیچ دڵخوازێک نییە", "workspace.addFavorite": "زیادکردن بۆ دڵخوازەکان", "workspace.removeFavorite": "لابردن لە دڵخوازەکان", "workspace.open": "کردنەوە", "workspace.restore": "گەڕاندنەوە", "workspace.restoreConfirm": "ئەم وەشانە بگەڕێنرێتەوە؟ پێشتر وەشانێکی پارێزراوی دۆخی ئێستا دروست دەکرێت.", "workspace.restoreSuccess": "وەشانەکە بە سەلامەتی گەڕێندرایەوە", "workspace.historyEmpty": "هێشتا هیچ وەشانێکی پاشەکەوتکراو نییە", "workspace.revision": "وەشانی {value}", "workspace.autosaveVersion": "پاشەکەوتی خۆکار", "workspace.manualVersion": "پاشەکەوتی دەستی", "workspace.restoreVersion": "وەشانی گەڕێندراوە", "workspace.searchPlaceholder": "گەڕان لە پڕۆژە، ژوور، دیوار و تۆمارەکان", "workspace.searchEmpty": "بۆ گەڕان لە شوێنی کار دەست بە نووسین بکە", "workspace.searchNoResults": "هیچ تۆمارێکی گونجاو نەدۆزرایەوە", "workspace.recentSearches": "گەڕانە نوێیەکان", "workspace.clearSearch": "سڕینەوە", "workspace.openFavorites": "کردنەوەی دڵخوازەکان", "workspace.preferences": "ڕێکخستنەکانی شوێنی کار", "workspace.customiseActions": "کردارە خێراکان هەڵبژێرە", "workspace.saveFailed": "گۆڕانکارییەکانت پاشەکەوت نەکران؛ لەم شوێنەی کاردا بەردەستن.", "workspace.saveSuccess": "پڕۆژە پاشەکەوت کرا", "workspace.discardConfirm": "گۆڕانکاری پاشەکەوت نەکراوت هەیە. بەردەوام بیت و فریبدەیت؟", "workspace.keyboardHint": "Ctrl/Cmd + K", "workspace.close": "داخستنی پانێڵی شوێنی کار", "workspace.loading": "شوێنی کار بار دەکرێت…",
  },
  ar: {
    "workspace.heading": "مساحة العمل", "workspace.description": "مساحة مشروعك الحية", "workspace.saved": "تم الحفظ", "workspace.saving": "جارٍ الحفظ…", "workspace.unsaved": "تغييرات غير محفوظة", "workspace.failed": "فشل الحفظ", "workspace.autosave": "حفظ تلقائي", "workspace.manualSave": "حفظ", "workspace.newProject": "مشروع جديد", "workspace.search": "بحث", "workspace.favorites": "المفضلة", "workspace.history": "السجل", "workspace.notifications": "الإشعارات", "workspace.markAllRead": "تعليم الكل كمقروء", "workspace.noNotifications": "لا توجد إشعارات", "workspace.recentProjects": "المشاريع الأخيرة", "workspace.recentActivity": "النشاط الأخير", "workspace.statistics": "إحصاءات مساحة العمل", "workspace.projectsCount": "المشاريع المحفوظة", "workspace.roomsCount": "الغرف", "workspace.wallsCount": "الجدران", "workspace.noFavorites": "لا توجد عناصر مفضلة بعد", "workspace.addFavorite": "إضافة إلى المفضلة", "workspace.removeFavorite": "إزالة من المفضلة", "workspace.open": "فتح", "workspace.restore": "استعادة", "workspace.restoreConfirm": "هل تريد استعادة هذا الإصدار؟ سيتم إنشاء نسخة استرداد للحالة الحالية أولاً.", "workspace.restoreSuccess": "تمت استعادة الإصدار بأمان", "workspace.historyEmpty": "لا توجد إصدارات محفوظة بعد", "workspace.revision": "الإصدار {value}", "workspace.autosaveVersion": "حفظ تلقائي", "workspace.manualVersion": "حفظ يدوي", "workspace.restoreVersion": "إصدار مستعاد", "workspace.searchPlaceholder": "ابحث في المشاريع والغرف والجدران والسجلات المحفوظة", "workspace.searchEmpty": "ابدأ بالكتابة للبحث في مساحة العمل", "workspace.searchNoResults": "لا توجد سجلات مطابقة", "workspace.recentSearches": "عمليات البحث الأخيرة", "workspace.clearSearch": "مسح", "workspace.openFavorites": "فتح المفضلة", "workspace.preferences": "تفضيلات مساحة العمل", "workspace.customiseActions": "اختر الإجراءات السريعة", "workspace.saveFailed": "تعذر حفظ تغييراتك. تبقى مفتوحة في مساحة العمل.", "workspace.saveSuccess": "تم حفظ المشروع", "workspace.discardConfirm": "لديك تغييرات غير محفوظة. هل تريد المتابعة وتجاهلها؟", "workspace.keyboardHint": "Ctrl/Cmd + K", "workspace.close": "إغلاق لوحة مساحة العمل", "workspace.loading": "جارٍ تحميل مساحة العمل…",
  },
};
