import { auditEvent } from "@/lib/audit";
import { authenticatedUser, hasPermission } from "@/lib/auth";
import { apiError, apiHeaders } from "@/lib/observability";
import { deleteServerProject, getServerProject, saveServerProject } from "@/lib/server-projects";
import { limitedJson, sameOrigin } from "@/lib/verification-auth";
import { verificationStore } from "@/lib/verification-store";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
type Context = { params: Promise<{ projectId: string }> };
export async function GET(request: Request, { params }: Context) { try { const store = verificationStore(); const user = await authenticatedUser(store, request); const id = (await params).projectId; if (!user || !hasPermission(user.role, "projects.read")) return apiError("UNAUTHORIZED", 401, request); const project = await getServerProject(store, user, id); return project ? Response.json({ project }, { headers: apiHeaders(request) }) : apiError("NOT_FOUND", 404, request); } catch { return apiError("DEPENDENCY_UNAVAILABLE", 503, request); } }
export async function PUT(request: Request, { params }: Context) { if (!sameOrigin(request)) return apiError("FORBIDDEN", 403, request); try { const store = verificationStore(); const user = await authenticatedUser(store, request); const id = (await params).projectId; if (!user || !hasPermission(user.role, "projects.update")) return apiError("FORBIDDEN", 403, request); const body = await limitedJson(request) as { project?: unknown }; if (!body.project || typeof body.project !== "object" || (body.project as { id?: unknown }).id !== id) return apiError("VALIDATION_ERROR", 400, request); const exists = await getServerProject(store, user, id); if (!exists) return apiError("NOT_FOUND", 404, request); const result = await saveServerProject(store, user, body.project); await store.appendAudit(auditEvent({ action: "project.updated", entityType: "project", entityReference: id, result: "success", context: { actorId: user.id } })); return Response.json(result, { headers: apiHeaders(request) }); } catch { return apiError("VALIDATION_ERROR", 400, request); } }
export async function DELETE(request: Request, { params }: Context) { if (!sameOrigin(request)) return apiError("FORBIDDEN", 403, request); try { const store = verificationStore(); const user = await authenticatedUser(store, request); const id = (await params).projectId; if (!user || !hasPermission(user.role, "projects.delete")) return apiError("FORBIDDEN", 403, request); if (!(await deleteServerProject(store, user, id))) return apiError("NOT_FOUND", 404, request); await store.appendAudit(auditEvent({ action: "project.deleted", entityType: "project", entityReference: id, result: "success", context: { actorId: user.id } })); return new Response(null, { status: 204, headers: apiHeaders(request) }); } catch { return apiError("DEPENDENCY_UNAVAILABLE", 503, request); } }
