import type { CalculatorProjectData, OpeningInput } from "../types/index.ts";
export type PlanRect = { id: string; kind: "room" | "wall"; name: string; x: number; y: number; width: number; height: number; openings: Array<PlanOpening> };
export type PlanOpening = { id: string; kind: "door" | "window"; x: number; y: number; width: number; height: number; hostId: string };
export type PlanBounds = { minX: number; minY: number; maxX: number; maxY: number };
export type PlanViewport = { centerX: number; centerY: number; zoom: number };
const number = (value: string) => Number(value);
const valid = (value: number) => Number.isFinite(value) && value > 0;
function openings(items: OpeningInput[], kind: "door" | "window", room: { id: string; x: number; y: number; width: number }) {
  return items.flatMap((item) => { const width = number(item.width); const height = number(item.height); const position = number(item.horizontalPosition); if (![width, height, position].every(Number.isFinite) || !valid(width) || !valid(height)) return []; const x = room.x + Math.max(0, Math.min(room.width - width, position)); return [{ id: item.id, kind, x, y: room.y, width: Math.min(width, room.width), height, hostId: room.id }]; });
}
/** Derived world-metre geometry. It never stores pixels or mutates project data. */
export function buildFloorPlan(data: CalculatorProjectData): PlanRect[] {
  if (data.mode === "walls") return data.walls.flatMap((wall, index) => { const length = number(wall.length); if (!valid(length)) return []; const rect = { id: wall.id, kind: "wall" as const, name: wall.name || `Wall ${index + 1}`, x: index * 1.5, y: 0, width: 0.2, height: length, openings: [] as PlanOpening[] }; return [{ ...rect, openings: [...openings(wall.doors, "door", { ...rect, width: rect.height }), ...openings(wall.windows, "window", { ...rect, width: rect.height })] }]; });
  let cursor = 0; return data.rooms.flatMap((room, index) => { const width = number(room.length); const height = number(room.width); if (!valid(width) || !valid(height)) return []; const rect = { id: room.id, kind: "room" as const, name: room.name || `Room ${index + 1}`, x: cursor, y: 0, width, height, openings: [] as PlanOpening[] }; cursor += width + 1; return [{ ...rect, openings: [...openings(room.doors, "door", rect), ...openings(room.windows, "window", rect)] }]; });
}
export function planBounds(plan: PlanRect[]): PlanBounds { if (!plan.length) return { minX: 0, minY: 0, maxX: 10, maxY: 10 }; return { minX: Math.min(...plan.map((item) => item.x)), minY: Math.min(...plan.map((item) => item.y)), maxX: Math.max(...plan.map((item) => item.x + item.width)), maxY: Math.max(...plan.map((item) => item.y + item.height)) }; }
export function fitPlan(plan: PlanRect[], aspect = 1): PlanViewport { const bounds = planBounds(plan); const width = Math.max(1, bounds.maxX - bounds.minX); const height = Math.max(1, bounds.maxY - bounds.minY); return { centerX: (bounds.minX + bounds.maxX) / 2, centerY: (bounds.minY + bounds.maxY) / 2, zoom: Math.min(20, Math.max(0.05, Math.min(16 / width, (16 / Math.max(aspect, 0.1)) / height))) }; }
export function viewBox(viewport: PlanViewport, aspect: number) { const zoom = Number.isFinite(viewport.zoom) ? Math.min(20, Math.max(0.05, viewport.zoom)) : 1; const width = 16 / zoom; const height = width / Math.max(aspect, 0.1); return { x: viewport.centerX - width / 2, y: viewport.centerY - height / 2, width, height }; }
export function screenToWorld(clientX: number, clientY: number, rect: { left: number; top: number; width: number; height: number }, viewport: PlanViewport) { const box = viewBox(viewport, rect.width / rect.height); return { x: box.x + ((clientX - rect.left) / rect.width) * box.width, y: box.y + ((clientY - rect.top) / rect.height) * box.height }; }
export function measure(a: { x: number; y: number }, b: { x: number; y: number }) { return Math.hypot(b.x - a.x, b.y - a.y); }
export function hitPlan(plan: PlanRect[], point: { x: number; y: number }) { for (const item of plan) { const opening = item.openings.find((candidate) => point.x >= candidate.x && point.x <= candidate.x + candidate.width && point.y >= candidate.y - 0.2 && point.y <= candidate.y + 0.2); if (opening) return { kind: opening.kind, id: opening.id, hostId: item.id }; if (point.x >= item.x && point.x <= item.x + item.width && point.y >= item.y && point.y <= item.y + item.height) return { kind: item.kind, id: item.id }; } return null; }
