import type { CalculatorProjectData, OpeningInput, RoomInput, RoomWallInput, WallInput } from "@/features/calculator/types";

let idSequence = 0;
function createId(prefix: string): string { idSequence += 1; return `${prefix}-${idSequence}`; }
export function createOpening(wallId = ""): OpeningInput { return { id: createId("opening"), name: "", width: "", height: "", quantity: "1", widthUnit: "m", heightUnit: "m", wallId, horizontalPosition: "", horizontalPositionUnit: "m", sillHeight: "0", sillHeightUnit: "m" }; }
function createRoomWall(name: string): RoomWallInput { return { id: createId("room-wall"), name, enabled: true, wallType: "interior", doors: [], windows: [], otherOpenings: [], structuralDeductions: [] }; }
export function createRoom(): RoomInput { return { id: createId("room"), name: "", length: "", width: "", height: "", lengthUnit: "m", widthUnit: "m", heightUnit: "m", doors: [], windows: [], walls: [createRoomWall("دیوار ١"), createRoomWall("دیوار ٢"), createRoomWall("دیوار ٣"), createRoomWall("دیوار ٤")] }; }
export function createWall(): WallInput { return { id: createId("wall"), name: "", length: "", height: "", lengthUnit: "m", heightUnit: "m", doors: [], windows: [] }; }
export function createDefaultProject(): CalculatorProjectData { idSequence = 0; return { mode: "rooms", metadata: { projectName: "", ownerName: "", location: "", notes: "" }, rooms: [createRoom()], walls: [createWall()], settings: { blockMode: "library", selectedBlockId: "20cm", customBlock: { thicknessCm: 20, lengthCm: 40, heightCm: 20 }, customBlockUnit: "cm", mortarJointUnit: "cm", areaDisplayUnit: "m²", volumeDisplayUnit: "m³", wastePreset: "5", customWastePercentage: "", unitPrice: "", currency: "IQD", exchangeRateIqdPerUsd: "", exchangeRateSource: "", exchangeRateUpdatedAt: "", mortarEnabled: false, mortarConsumptionM3PerM2: "", cementRatio: "", interfaceMode: "quick", mortarJointEnabled: false, mortarJointThicknessCm: "", transportCost: "", laborCost: "", mortarCost: "", otherCostLabel: "", otherCost: "" } }; }
