import type { CalculatorProjectData, OpeningInput, RoomInput, RoomWallInput, WallInput } from "@/features/calculator/types";

let idSequence = 0;
function createId(prefix: string): string { idSequence += 1; return `${prefix}-${idSequence}`; }
export function createOpening(wallId = ""): OpeningInput { return { id: createId("opening"), name: "", width: "", height: "", quantity: "1", widthUnit: "m", heightUnit: "m", wallId, horizontalPosition: "", horizontalPositionUnit: "m", sillHeight: "0", sillHeightUnit: "m" }; }
function createRoomWall(name: string): RoomWallInput { return { id: createId("room-wall"), name, enabled: true, wallType: "interior", thickness: "0.2", thicknessUnit: "m", notes: "", doors: [], windows: [], otherOpenings: [], structuralDeductions: [] }; }
export function createRoom(): RoomInput { return { id: createId("room"), name: "", length: "", width: "", height: "", lengthUnit: "m", widthUnit: "m", heightUnit: "m", doors: [], windows: [], walls: [createRoomWall("دیوار ١"), createRoomWall("دیوار ٢"), createRoomWall("دیوار ٣"), createRoomWall("دیوار ٤")] }; }
export function createWall(): WallInput { return { id: createId("wall"), name: "", length: "", height: "", thickness: "0.2", lengthUnit: "m", heightUnit: "m", thicknessUnit: "m", wallType: "interior", notes: "", doors: [], windows: [] }; }
export function duplicateRoom(source: RoomInput): RoomInput {
  const fresh = createRoom();
  const wallIds = new Map(source.walls.map((wall, index) => [wall.id, fresh.walls[index]?.id ?? createId("room-wall")]));
  const copyOpenings = (openings: OpeningInput[]) => openings.map((opening) => ({ ...opening, id: createId("opening"), wallId: wallIds.get(opening.wallId) ?? opening.wallId }));
  return { ...source, id: fresh.id, name: source.name ? `${source.name} copy` : "", doors: copyOpenings(source.doors), windows: copyOpenings(source.windows), walls: source.walls.map((wall) => ({ ...wall, id: wallIds.get(wall.id) ?? createId("room-wall"), doors: copyOpenings(wall.doors), windows: copyOpenings(wall.windows), otherOpenings: copyOpenings(wall.otherOpenings), structuralDeductions: copyOpenings(wall.structuralDeductions) })) };
}
export function createDefaultProject(): CalculatorProjectData { idSequence = 0; return { mode: "rooms", metadata: { projectName: "", projectNumber: "", ownerName: "", clientName: "", location: "", description: "", status: "draft", measurementSystem: "metric", notes: "" }, rooms: [createRoom()], walls: [createWall()], settings: { blockMode: "library", selectedBlockId: "20cm", customBlock: { thicknessCm: 20, lengthCm: 40, heightCm: 20 }, customBlockUnit: "cm", mortarJointUnit: "cm", areaDisplayUnit: "m²", volumeDisplayUnit: "m³", wastePreset: "5", customWastePercentage: "", unitPrice: "", currency: "IQD", exchangeRateIqdPerUsd: "", exchangeRateSource: "", exchangeRateUpdatedAt: "", mortarEnabled: false, mortarConsumptionM3PerM2: "", cementRatio: "", interfaceMode: "quick", mortarJointEnabled: false, mortarJointThicknessCm: "", transportCost: "", laborCost: "", mortarCost: "", otherCostLabel: "", otherCost: "" } }; }
