import { auditEvent } from "@/lib/audit";
import { authenticatedUser, createUser, hasPermission, listUsers } from "@/lib/auth";
import { roles, type Role } from "@/lib/auth-types";
import { apiError, apiHeaders } from "@/lib/observability";
import { limitedJson, sameOrigin } from "@/lib/verification-auth";
import { verificationStore } from "@/lib/verification-store";
export const runtime = "nodejs";
async function actor(request: Request) { const store = verificationStore(); const user = await authenticatedUser(store, request); return { store, user }; }
function mayManage(role: Role, target: Role) { return role === "SUPER_ADMIN" || (role === "ADMIN" && !["SUPER_ADMIN", "ADMIN"].includes(target)); }
export async function GET(request: Request) { try { const { store, user } = await actor(request); if (!user) return apiError("UNAUTHORIZED", 401, request); if (!hasPermission(user.role, "users.read")) return apiError("FORBIDDEN", 403, request); return Response.json({ users: await listUsers(store) }, { headers: apiHeaders(request) }); } catch { return apiError("DEPENDENCY_UNAVAILABLE", 503, request); } }
export async function POST(request: Request) { if (!sameOrigin(request)) return apiError("FORBIDDEN", 403, request); try { const { store, user } = await actor(request); if (!user) return apiError("UNAUTHORIZED", 401, request); if (!hasPermission(user.role, "users.create")) return apiError("FORBIDDEN", 403, request); const body = await limitedJson(request) as { email?: unknown; displayName?: unknown; password?: unknown; role?: unknown }; if (typeof body.email !== "string" || typeof body.displayName !== "string" || typeof body.password !== "string" || !roles.includes(body.role as Role) || !mayManage(user.role, body.role as Role)) return apiError("VALIDATION_ERROR", 400, request); const created = await createUser(store, { email: body.email, displayName: body.displayName, password: body.password, role: body.role as Role }); await store.appendAudit(auditEvent({ action: "auth.user.created", entityType: "user", entityReference: created.id, result: "success", context: { role: created.role } })); return Response.json({ user: created }, { status: 201, headers: apiHeaders(request) }); } catch (error) { return error instanceof Error && error.message === "User exists" ? apiError("CONFLICT", 409, request) : apiError("DEPENDENCY_UNAVAILABLE", 503, request); } }
