"use client";
import { Download, FileWarning, ListChecks } from "lucide-react";
import { useMemo } from "react";
import { buildEngineeringTakeoff, takeoffCsv } from "../lib/engineering-takeoff";
import type { CalculatorProjectData } from "../types";
import { useI18n } from "@/lib/i18n";
import { formatMoney } from "@/lib/currency";

export function EngineeringTakeoff({ data }: { data: CalculatorProjectData }) {
  const { t, formatNumber, direction } = useI18n(); const takeoff = useMemo(() => buildEngineeringTakeoff(data), [data]); const errors = takeoff.issues.filter((item) => item.severity === "ERROR");
  const download = () => { const blob = new Blob([takeoffCsv(takeoff)], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "blocksystem-boq.csv"; anchor.click(); URL.revokeObjectURL(url); };
  const amount = (value: number, currency?: "IQD" | "USD") => currency ? formatMoney(value, currency) : formatNumber(value, { maximumFractionDigits: 2 });
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6" dir={direction} aria-labelledby="engineering-title"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 id="engineering-title" className="flex items-center gap-2 text-xl font-bold"><ListChecks size={21}/>{t("engineering.title")}</h2><p className="mt-1 text-sm text-slate-600">{t("engineering.disclaimer")}</p></div><button type="button" onClick={download} disabled={!takeoff.boq.length} className="inline-flex min-h-11 items-center gap-2 rounded-lg border px-3 font-semibold disabled:opacity-50"><Download size={17}/>{t("engineering.export")}</button></div>
    <section className="mt-5" aria-live="polite"><h3 className="font-bold">{t("engineering.validation")}</h3>{takeoff.issues.length ? <ul className="mt-3 space-y-2">{takeoff.issues.map((issue, index) => <li key={`${issue.code}-${index}`} className={`rounded-lg border p-3 text-sm ${issue.severity === "ERROR" ? "border-red-200 bg-red-50" : issue.severity === "WARNING" ? "border-amber-200 bg-amber-50" : "border-blue-200 bg-blue-50"}`}><strong>{t(`engineering.${issue.severity.toLowerCase()}s`)}</strong> · {t(issue.messageKey)} <bdi dir="ltr">{issue.entityId}</bdi></li>)}</ul> : <p className="mt-3 rounded-lg bg-emerald-50 p-3 text-sm">{t("engineering.noIssues")}</p>}</section>
    {errors.length ? <div className="mt-5 flex gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800"><FileWarning size={18}/>{t("engineering.blocked")}</div> : null}
    {takeoff.result ? <><section className="mt-6"><h3 className="font-bold">{t("engineering.takeoff")}</h3><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-lg bg-slate-50 p-3"><dt>{t("results.gross")}</dt><dd dir="ltr" className="font-bold">{formatNumber(takeoff.result.grossWallArea, { maximumFractionDigits: 3 })} m²</dd></div><div className="rounded-lg bg-slate-50 p-3"><dt>{t("results.openings")}</dt><dd dir="ltr" className="font-bold">{formatNumber(takeoff.result.totalOpeningArea, { maximumFractionDigits: 3 })} m²</dd></div><div className="rounded-lg bg-slate-50 p-3"><dt>{t("results.net")}</dt><dd dir="ltr" className="font-bold">{formatNumber(takeoff.result.netWallArea, { maximumFractionDigits: 3 })} m²</dd></div><div className="rounded-lg bg-slate-50 p-3"><dt>{t("engineering.final")}</dt><dd className="font-bold">{formatNumber(takeoff.result.recommendedBlocks)}</dd></div></dl></section>
      <section className="mt-6"><h3 className="font-bold">{t("engineering.boq")}</h3><div className="mt-3 overflow-x-auto"><table className="min-w-[42rem] w-full text-sm"><thead><tr className="border-b text-start"><th>#</th><th>{t("common.name")}</th><th>{t("engineering.final")}</th><th>{t("engineering.unitRate")}</th><th>{t("engineering.amount")}</th><th>{t("engineering.trace")}</th></tr></thead><tbody>{takeoff.boq.map((row) => <tr key={row.number} className="border-b"><td><bdi dir="ltr">{row.number}</bdi></td><td>{row.description}</td><td><bdi dir="ltr">{formatNumber(row.quantity)}</bdi> {row.unit}</td><td dir="ltr">{row.unitRate === undefined ? "—" : amount(row.unitRate, row.currency)}</td><td dir="ltr">{amount(row.amount, row.currency)}</td><td>{row.trace}</td></tr>)}</tbody></table></div>{takeoff.result.cost ? <p className="mt-3 text-end font-bold" dir="ltr">{t("results.totalCost")}: {amount(takeoff.result.cost.grandTotal, takeoff.result.cost.currency)}</p> : null}</section>
      <section className="mt-6"><h3 className="font-bold">{t("engineering.openings")}</h3>{takeoff.openings.length ? <div className="mt-3 overflow-x-auto"><table className="min-w-[36rem] w-full text-sm"><thead><tr className="border-b text-start"><th>{t("common.name")}</th><th>{t("common.wall")}</th><th>{t("common.width")}</th><th>{t("common.height")}</th><th>{t("common.area")}</th></tr></thead><tbody>{takeoff.openings.map((opening) => <tr key={opening.id} className="border-b"><td>{opening.name}</td><td>{opening.host}</td><td dir="ltr">{formatNumber(opening.width)} m</td><td dir="ltr">{formatNumber(opening.height)} m</td><td dir="ltr">{formatNumber(opening.area, { maximumFractionDigits: 3 })} m²</td></tr>)}</tbody></table></div> : <p className="mt-3 text-sm text-slate-600">—</p>}</section>
      {takeoff.scenarios.length ? <section className="mt-6"><h3 className="font-bold">{t("engineering.scenarios")}</h3><ul className="mt-3 grid gap-2 sm:grid-cols-2">{takeoff.scenarios.map((scenario) => <li key={scenario.id} className="rounded-lg bg-slate-50 p-3"><strong>{scenario.name}</strong><span className="block" dir="ltr">{formatNumber(scenario.blocks)} pcs · {scenario.total === undefined ? "—" : amount(scenario.total, scenario.currency)}</span></li>)}</ul></section> : null}</> : null}
  </section>;
}
