import type { ProjectMetadata } from "@/features/calculator/types";
import { useI18n } from "@/lib/i18n";

interface ProjectInformationProps { metadata: ProjectMetadata; onChange: (next: ProjectMetadata) => void; }
const statuses = ["draft", "active", "completed", "archived"] as const;

export function ProjectInformation({ metadata, onChange }: ProjectInformationProps) {
  const { t } = useI18n();
  const field = (key: keyof ProjectMetadata, label: string, multiline = false) => <div className="form-field"><label htmlFor={`project-${key}`} className="form-label">{label}</label>{multiline ? <textarea id={`project-${key}`} value={metadata[key] as string} onChange={(event) => onChange({ ...metadata, [key]: event.target.value })} rows={3} className="form-control min-h-24 px-3 py-2" /> : <input id={`project-${key}`} value={metadata[key] as string} onChange={(event) => onChange({ ...metadata, [key]: event.target.value })} className="form-control px-3" />}</div>;
  return <details className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><summary className="cursor-pointer text-lg font-bold text-slate-950">{t("projectInfo.heading")}</summary><div className="mt-5 grid gap-4 sm:grid-cols-2">{field("projectName", t("projectInfo.projectName"))}{field("projectNumber", t("project.number"))}{field("ownerName", t("projectInfo.owner"))}{field("clientName", t("project.client"))}{field("location", t("projectInfo.location"))}<div className="form-field"><label htmlFor="project-status" className="form-label">{t("project.status")}</label><select id="project-status" value={metadata.status} onChange={(event) => onChange({ ...metadata, status: event.target.value as ProjectMetadata["status"] })} className="form-control px-3">{statuses.map((status) => <option key={status} value={status}>{t(`project.${status}`)}</option>)}</select></div><div className="form-field"><label htmlFor="project-measurementSystem" className="form-label">{t("project.measurement")}</label><select id="project-measurementSystem" value={metadata.measurementSystem} onChange={(event) => onChange({ ...metadata, measurementSystem: event.target.value as ProjectMetadata["measurementSystem"] })} className="form-control px-3"><option value="metric">{t("project.metric")}</option><option value="imperial">{t("project.imperial")}</option></select></div>{field("description", t("project.description"), true)}{field("notes", t("projectInfo.notes"), true)}</div></details>;
}
