"use client";

import { MessageSquare, RefreshCw, Share2, Users } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { useAuth } from "@/components/auth/auth-provider";
import { useI18n } from "@/lib/i18n";
import type { ProjectRole } from "@/lib/collaboration";

type Person = { id: string; displayName: string; email?: string; status: string };
type Data = { initialized?: boolean; ownerId: string; revision: number; members: Array<{ userId: string; role: ProjectRole }>; comments: Array<{ id: string; authorId: string; content: string; createdAt: string; updatedAt?: string; parentCommentId?: string }>; assignments: Array<{ assigneeId: string }>; activity: Array<{ id: string; actorId: string; action: string; createdAt: string; detail?: string }>; people: Record<string, Person> };
export function ProjectCollaboration({ projectId }: { projectId: string | null }) {
  const { t, direction, formatDate } = useI18n(); const { user } = useAuth(); const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [comment, setComment] = useState(""); const [replyTo, setReplyTo] = useState<string | null>(null); const [query, setQuery] = useState(""); const [results, setResults] = useState<Person[]>([]);
  const load = useCallback(async () => { if (!projectId || !user) return; setLoading(true); try { const response = await fetch(`/api/collaboration/projects/${encodeURIComponent(projectId)}`, { cache: "no-store" }); if (!response.ok) { setError(t("collab.unavailable")); return; } const next = await response.json() as Data; setData(next.initialized === false ? null : next); setError(""); } catch { setError(t("collab.offline")); } finally { setLoading(false); } }, [projectId, t, user]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const action = async (body: Record<string, unknown>) => { if (!projectId) return; if (!navigator.onLine) { setError(t("collab.offline")); return; } try { const response = await fetch(`/api/collaboration/projects/${encodeURIComponent(projectId)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...body, ...(data ? { expectedVersion: data.revision } : {}) }) }); if (response.status === 409) { setError(t("collab.conflict")); return; } if (!response.ok) { setError(t("collab.unavailable")); return; } const next = await response.json() as Data & { initialized?: boolean }; if (next.initialized && !next.members) await load(); else setData(next); setError(""); } catch { setError(t("collab.offline")); } };
  const search = async () => { if (!projectId || query.trim().length < 2) return; const response = await fetch(`/api/collaboration/projects/${encodeURIComponent(projectId)}?search=${encodeURIComponent(query)}`, { cache: "no-store" }); if (response.ok) setResults((await response.json() as { users: Person[] }).users); };
  if (!projectId || !user) return null;
  const own = data?.members.find((member) => member.userId === user.id); const manages = user.role === "SUPER_ADMIN" || user.role === "ADMIN" || own?.role === "OWNER"; const comments = data?.comments ?? [];
  return <section className="rounded-xl border border-slate-200 bg-white p-4 sm:p-6" dir={direction} aria-labelledby="collaboration-title">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 id="collaboration-title" className="flex items-center gap-2 text-xl font-bold text-[#0F2053]"><Share2 size={20}/>{t("collab.title")}</h2><p className="mt-1 text-sm text-slate-600">{t("collab.presence")}</p></div><button type="button" onClick={() => void load()} className="inline-flex min-h-11 items-center gap-2 rounded-lg border px-3 font-semibold"><RefreshCw size={17}/>{t("collab.reload")}</button></div>
    {error ? <div className="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm" role="alert">{error}</div> : null}
    {!data ? <div className="mt-5 rounded-lg border border-dashed p-4"><p className="text-sm text-slate-600">{loading ? t("auth.loading") : t("collab.noMembers")}</p><button type="button" onClick={() => void action({ action: "initialize" })} className="mt-3 min-h-11 rounded-lg bg-[#0F2053] px-4 font-bold text-[#EDE6CC]">{t("collab.enable")}</button></div> : <div className="mt-5 grid gap-6 lg:grid-cols-2">
      <div className="space-y-5"><section><h3 className="flex items-center gap-2 font-bold"><Users size={18}/>{t("collab.members")}</h3><div className="mt-3 space-y-2">{data.members.map((member) => <div key={member.userId} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-slate-50 p-3"><span className="min-w-0"><strong className="block truncate">{data.people[member.userId]?.displayName ?? "—"}</strong><bdi className="block break-all text-xs text-slate-600" dir="ltr">{data.people[member.userId]?.email}</bdi></span><span className="text-sm font-semibold">{t(`collab.${member.role.toLowerCase()}`)}</span>{manages && member.role !== "OWNER" ? <button type="button" onClick={() => void action({ action: "member.remove", userId: member.userId })} className="min-h-10 rounded-md border px-2 text-sm">{t("collab.remove")}</button> : null}</div>)}</div></section>
        {manages ? <section className="rounded-lg border p-3"><label className="grid gap-1 text-sm">{t("collab.search")}<input className="form-control" value={query} onChange={(event) => setQuery(event.target.value)} onBlur={() => void search()} /></label>{results.map((person) => <div key={person.id} className="mt-2 flex items-center justify-between gap-2 text-sm"><span><strong>{person.displayName}</strong><bdi className="ms-2" dir="ltr">{person.email}</bdi></span><button type="button" onClick={() => void action({ action: "member.add", userId: person.id, role: "EDITOR" })} className="min-h-10 rounded-md border px-2">{t("collab.addMember")}</button></div>)}</section> : null}
        <section><h3 className="font-bold">{t("collab.assignment")}</h3><p className="mt-2 text-sm text-slate-600">{data.assignments.length ? data.assignments.map((item) => data.people[item.assigneeId]?.displayName).join(", ") : t("collab.noMembers")}</p></section></div>
      <div className="space-y-5"><section><h3 className="flex items-center gap-2 font-bold"><MessageSquare size={18}/>{t("collab.comments")}</h3>{comments.length ? <div className="mt-3 space-y-3">{comments.map((item) => <article key={item.id} className={`rounded-lg border p-3 ${item.parentCommentId ? "ms-4" : ""}`}><header className="flex flex-wrap justify-between gap-2 text-sm"><strong>{data.people[item.authorId]?.displayName ?? "—"}</strong><time>{formatDate(item.createdAt, { dateStyle: "medium", timeStyle: "short" })}</time></header><p className="mt-2 whitespace-pre-wrap text-sm">{item.content}</p>{own && own.role !== "VIEWER" ? <button type="button" onClick={() => setReplyTo(item.id)} className="mt-2 min-h-10 text-sm font-semibold underline">{t("collab.reply")}</button> : null}{replyTo === item.id ? <form onSubmit={(event) => { event.preventDefault(); void action({ action: "comment", content: comment, parentCommentId: item.id }); setComment(""); setReplyTo(null); }} className="mt-2 flex gap-2"><input className="form-control min-w-0" value={comment} onChange={(event) => setComment(event.target.value)} required /><button className="min-h-10 rounded-md border px-3">{t("collab.send")}</button></form> : null}</article>)}</div> : <p className="mt-3 text-sm text-slate-600">{t("collab.noComments")}</p>}{own && own.role !== "VIEWER" ? <form onSubmit={(event) => { event.preventDefault(); void action({ action: "comment", content: comment }); setComment(""); }} className="mt-3 flex flex-col gap-2 sm:flex-row"><input className="form-control" value={comment} onChange={(event) => setComment(event.target.value)} placeholder="@member@example.com" required maxLength={4000}/><button className="min-h-11 rounded-lg bg-[#0F2053] px-4 font-bold text-[#EDE6CC]">{t("collab.send")}</button></form> : null}</section>
        <section><h3 className="font-bold">{t("collab.activity")}</h3>{data.activity.length ? <ol className="mt-3 space-y-2 text-sm">{data.activity.slice(0, 10).map((item) => <li key={item.id} className="rounded-lg bg-slate-50 p-3"><strong>{data.people[item.actorId]?.displayName ?? "—"}</strong> · <bdi dir="ltr">{item.action}</bdi> · {formatDate(item.createdAt, { dateStyle: "medium", timeStyle: "short" })}</li>)}</ol> : <p className="mt-3 text-sm text-slate-600">{t("collab.noActivity")}</p>}</section></div>
    </div>}
  </section>;
}
