"use client";

import { ArchiveRestore, Copy, Download, FolderOpen, Pencil, Save, Star, Trash2, Upload } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import type { CalculatorProjectData, SavedProject } from "@/features/calculator/types";
import { migrateSavedProject } from "@/lib/project-schema";
import { deleteSavedProject, duplicateProject, getFavorites, getSavedProjects, recordProjectOpen, renameSavedProject, setProjectStatus, subscribeToSavedProjects, toggleFavorite } from "@/lib/project-storage";
import { useI18n } from "@/lib/i18n";

interface Props { data: CalculatorProjectData; activeProjectId: string | null; onSave: () => void; onLoad: (data: CalculatorProjectData, projectId: string) => void; onNew: () => void; }
type SortOrder = "updated" | "created" | "name";

export function SavedProjects({ data, activeProjectId, onSave, onLoad, onNew }: Props) {
  const { t, formatDate } = useI18n();
  const [projects, setProjects] = useState<SavedProject[]>([]);
  const [favorites, setFavorites] = useState<string[]>([]);
  const [query, setQuery] = useState("");
  const [sort, setSort] = useState<SortOrder>("updated");
  const [status, setStatus] = useState<"all" | CalculatorProjectData["metadata"]["status"]>("all");
  const [message, setMessage] = useState("");
  const input = useRef<HTMLInputElement>(null);
  const refresh = () => { setProjects(getSavedProjects()); setFavorites(getFavorites()); };
  useEffect(() => { const timer = window.setTimeout(refresh, 0); const unsubscribe = subscribeToSavedProjects(refresh); return () => { window.clearTimeout(timer); unsubscribe(); }; }, []);
  const exportProject = () => { const blob = new Blob([JSON.stringify({ schemaVersion: 4, data }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${data.metadata.projectName || "project"}.json`; link.click(); URL.revokeObjectURL(url); };
  const importProject = async (file: File) => { try { const raw: unknown = JSON.parse(await file.text()); const imported = migrateSavedProject({ version: 4, id: "import", data: (raw as { data?: unknown }).data ?? raw }); if (!imported) throw new Error("invalid project"); onLoad(imported.data, ""); setMessage(t("workspace.saved")); } catch { setMessage(t("projects.importFailed")); } };
  const visible = projects.filter((project) => project.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()) && (status === "all" || project.data.metadata.status === status)).sort((left, right) => sort === "name" ? left.name.localeCompare(right.name) : new Date(sort === "created" ? right.createdAt ?? right.savedAt : right.savedAt).getTime() - new Date(sort === "created" ? left.createdAt ?? left.savedAt : left.savedAt).getTime());
  return <section id="projects" className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><FolderOpen size={20} className="text-amber-700" /><h2 className="text-xl font-bold">{t("projects.heading")}</h2></div><p className="mt-1 text-sm text-slate-600">{t("projects.description")}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={onNew} className="min-h-11 rounded-lg border border-slate-300 px-3 text-sm font-semibold">{t("projects.new")}</button><button type="button" onClick={onSave} className="inline-flex min-h-11 items-center gap-1 rounded-lg bg-slate-900 px-3 text-sm font-semibold text-white"><Save size={17} /> {t("projects.save")}</button><button type="button" onClick={exportProject} className="inline-flex min-h-11 items-center gap-1 rounded-lg border border-slate-300 px-3 text-sm font-semibold"><Download size={17} /> {t("projects.export")}</button><button type="button" onClick={() => input.current?.click()} className="inline-flex min-h-11 items-center gap-1 rounded-lg border border-slate-300 px-3 text-sm font-semibold"><Upload size={17} /> {t("projects.import")}</button><input ref={input} className="hidden" type="file" accept="application/json" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importProject(file); event.currentTarget.value = ""; }} /></div></div>
    {message ? <p className="mt-3 text-sm font-semibold text-emerald-700" role="status">{message}</p> : null}
    <div className="mt-4 grid gap-2 sm:grid-cols-[1fr_11rem_10rem]"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t("projects.search")} className="h-11 rounded-lg border border-slate-300 px-3" /><select value={sort} onChange={(event) => setSort(event.target.value as SortOrder)} className="h-11 rounded-lg border border-slate-300 px-3"><option value="updated">{t("projects.sortUpdated")}</option><option value="created">{t("projects.sortCreated")}</option><option value="name">{t("projects.sortName")}</option></select><select value={status} onChange={(event) => setStatus(event.target.value as typeof status)} className="h-11 rounded-lg border border-slate-300 px-3"><option value="all">{t("project.status")}</option>{(["draft", "active", "completed", "archived"] as const).map((item) => <option key={item} value={item}>{t(`project.${item}`)}</option>)}</select></div>
    <div className="mt-4 space-y-2">{visible.length === 0 ? <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-600">{t("projects.empty")}</p> : visible.map((project) => <div key={project.id} className={`flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3 ${project.id === activeProjectId ? "border-amber-400 bg-amber-50/50" : "border-slate-200"}`}><div><p className="font-bold">{project.name}</p><p className="text-xs text-slate-500">{t(`project.${project.data.metadata.status}`)} · {formatDate(project.savedAt, { dateStyle: "medium", timeStyle: "short" })}</p></div><div className="flex flex-wrap gap-1"><button type="button" onClick={() => { recordProjectOpen(project); onLoad(project.data, project.id); }} className="min-h-10 rounded-lg px-3 text-sm font-bold text-amber-800">{t("projects.open")}</button><button type="button" onClick={() => { if (!setProjectStatus(project.id, project.data.metadata.status === "archived" ? "active" : "archived")) setMessage(t("projects.saveFailed")); refresh(); }} className="grid size-10 place-items-center rounded-lg hover:bg-slate-100" aria-label={project.data.metadata.status === "archived" ? t("project.active") : t("project.archived")}><ArchiveRestore size={17} /></button><button type="button" onClick={() => { const favorite = toggleFavorite(project.id); if (favorite === null) { setMessage(t("projects.saveFailed")); return; } refresh(); }} className="grid size-10 place-items-center rounded-lg hover:bg-slate-100" aria-label={favorites.includes(project.id) ? t("workspace.removeFavorite") : t("workspace.addFavorite")}><Star size={17} fill={favorites.includes(project.id) ? "currentColor" : "none"} className={favorites.includes(project.id) ? "text-amber-500" : undefined} /></button><button type="button" onClick={() => { const name = window.prompt(t("projects.renamePrompt"), project.name)?.trim(); if (!name) return; if (!renameSavedProject(project.id, name)) { setMessage(t("projects.saveFailed")); return; } refresh(); }} className="grid size-10 place-items-center rounded-lg hover:bg-slate-100" aria-label={t("projects.rename")}><Pencil size={17} /></button><button type="button" onClick={() => { const copy = duplicateProject(project, t("projects.copySuffix")); if (!copy) { setMessage(t("projects.saveFailed")); return; } refresh(); }} className="grid size-10 place-items-center rounded-lg hover:bg-slate-100" aria-label={t("projects.duplicate")}><Copy size={17} /></button><button type="button" onClick={() => { if (!window.confirm(t("projects.confirmDelete"))) return; if (!deleteSavedProject(project.id)) { setMessage(t("projects.saveFailed")); return; } refresh(); }} className="grid size-10 place-items-center rounded-lg text-red-700 hover:bg-red-50" aria-label={t("common.delete")}><Trash2 size={17} /></button></div></div>)}</div>
  </section>;
}
