"use client";

import { Copy, FileDown, Plus, RotateCcw, Trash2 } from "lucide-react";
import { useMemo } from "react";
import { AppSelect } from "@/components/ui/app-select";
import { blockDefinitions } from "@/features/calculator/config/blocks";
import { calculateScenario, createScenarioFromProject, scenarioBlock, scenarioDelta } from "@/features/calculator/lib/scenario-engine";
import { downloadScenarioReport } from "@/features/calculator/lib/scenario-report";
import type { CalculationResult, CalculatorProjectData, ScenarioConfiguration } from "@/features/calculator/types";
import { formatMoney } from "@/lib/currency";
import { useI18n } from "@/lib/i18n";

type Props = { data: CalculatorProjectData; onChange: (next: CalculatorProjectData) => void };
const id = () => `scenario-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
const number = (value: number) => new Intl.NumberFormat("en-GB", { maximumFractionDigits: 2 }).format(value);

export function ScenarioComparison({ data, onChange }: Props) {
  const { t, formatNumber, language } = useI18n();
  const comparison = data.scenarioComparison ?? { scenarios: [] };
  const entries = useMemo(() => comparison.scenarios.map((scenario) => ({ scenario, response: calculateScenario(data, scenario) })), [comparison.scenarios, data]);
  const baseline = entries.find((entry) => entry.scenario.id === comparison.baselineScenarioId && entry.response.isValid);
  const update = (scenario: ScenarioConfiguration) => onChange({ ...data, scenarioComparison: { ...comparison, scenarios: comparison.scenarios.map((item) => item.id === scenario.id ? { ...scenario, updatedAt: new Date().toISOString() } : item) } });
  const add = () => { const scenario = createScenarioFromProject(data, id(), `${t("scenario.title")} ${comparison.scenarios.length + 1}`); onChange({ ...data, scenarioComparison: { ...comparison, scenarios: [...comparison.scenarios, scenario], activeScenarioId: scenario.id } }); };
  const duplicate = (source: ScenarioConfiguration) => { const now = new Date().toISOString(); const scenario = { ...source, id: id(), name: `${source.name} 2`, createdAt: now, updatedAt: now }; onChange({ ...data, scenarioComparison: { ...comparison, scenarios: [...comparison.scenarios, scenario], activeScenarioId: scenario.id } }); };
  const remove = (scenario: ScenarioConfiguration) => { if (!window.confirm(t("scenario.deleteConfirm"))) return; const scenarios = comparison.scenarios.filter((item) => item.id !== scenario.id); onChange({ ...data, scenarioComparison: { scenarios, baselineScenarioId: comparison.baselineScenarioId === scenario.id ? undefined : comparison.baselineScenarioId, activeScenarioId: comparison.activeScenarioId === scenario.id ? scenarios[0]?.id : comparison.activeScenarioId } }); };
  const reset = (scenario: ScenarioConfiguration) => update({ ...createScenarioFromProject(data, scenario.id, scenario.name), notes: scenario.notes, createdAt: scenario.createdAt });
  const selectBaseline = (scenario: ScenarioConfiguration) => onChange({ ...data, scenarioComparison: { ...comparison, baselineScenarioId: comparison.baselineScenarioId === scenario.id ? undefined : scenario.id } });
  const selectActive = (scenario: ScenarioConfiguration) => onChange({ ...data, scenarioComparison: { ...comparison, activeScenarioId: scenario.id } });
  const report = async () => {
    const valid = entries.filter((entry) => entry.response.isValid);
    if (!valid.length) return;
    await downloadScenarioReport({ projectName: data.metadata.projectName, scope: t("scenario.scope"), generatedAt: new Date().toISOString(), language,
      scenarios: valid.map(({ scenario, response }) => ({ name: scenario.name, block: scenarioBlock(scenario)?.name ?? "—", notes: scenario.notes, currency: response.isValid ? response.result.cost?.currency : undefined })),
      rows: [...metrics.map(([label, read, unit]) => ({ label: t(label), values: valid.map(({ response }) => response.isValid ? `${formatNumber(read(response.result), { maximumFractionDigits: 2 })} ${unit}` : "—") })), { label: t("scenario.total"), values: valid.map(({ response }) => response.isValid && response.result.cost ? formatMoney(response.result.cost.grandTotal, response.result.cost.currency) : "—") }],
    });
  };
  const metrics = [
    ["scenario.gross", (r: CalculationResult) => r.grossWallArea, "m²"],
    ["scenario.openings", (r: CalculationResult) => r.totalOpeningArea, "m²"],
    ["scenario.net", (r: CalculationResult) => r.netWallArea, "m²"],
    ["scenario.base", (r: CalculationResult) => r.requiredBlocks, ""],
    ["scenario.wasteBlocks", (r: CalculationResult) => r.wasteBlocks, ""],
    ["scenario.final", (r: CalculationResult) => r.recommendedBlocks, ""],
  ] as const;

  return <section className="print:hidden rounded-2xl border border-[#0F2053]/15 bg-white p-4 shadow-sm sm:p-6" aria-labelledby="scenario-comparison-title">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="scenario-comparison-title" className="text-xl font-bold text-[#0F2053]">{t("scenario.title")}</h2><p className="mt-1 text-sm text-slate-600">{t("scenario.description")}</p><p className="mt-1 text-xs font-medium text-slate-500">{t("scenario.scope")}: {data.metadata.projectName || "—"}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => void report()} disabled={!entries.some((entry) => entry.response.isValid)} className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-[#0F2053]/25 px-3 text-sm font-bold text-[#0F2053] disabled:opacity-50"><FileDown size={18}/>{t("scenario.report")}</button><button type="button" onClick={add} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#0F2053] px-3 text-sm font-bold text-[#EDE6CC]"><Plus size={18}/>{t("scenario.add")}</button></div></div>
    {!entries.length ? <div className="mt-5 rounded-xl border border-dashed border-slate-300 p-6 text-center"><p className="text-sm text-slate-600">{t("scenario.empty")}</p><button type="button" onClick={add} className="mt-4 min-h-11 rounded-lg bg-amber-600 px-4 text-sm font-bold text-white">{t("scenario.createFirst")}</button></div> : <>
      <div className="mt-5 grid gap-4 lg:grid-cols-2">
        {entries.map(({ scenario, response }) => { const result = response.isValid ? response.result : undefined; const cost = result?.cost; const quantityDelta = result && baseline?.response.isValid && scenario.id !== baseline.scenario.id ? scenarioDelta(result.recommendedBlocks, baseline.response.result.recommendedBlocks) : undefined; const moneyDelta = cost && baseline?.response.isValid && baseline.response.result.cost?.currency === cost.currency && scenario.id !== baseline.scenario.id ? scenarioDelta(cost.grandTotal, baseline.response.result.cost.grandTotal) : undefined;
          return <article key={scenario.id} className={`min-w-0 rounded-xl border p-4 ${comparison.activeScenarioId === scenario.id ? "border-amber-500 ring-1 ring-amber-200" : "border-slate-200"}`}>
            <div className="flex flex-wrap gap-2"><input aria-label={t("scenario.name")} value={scenario.name} onChange={(e) => update({ ...scenario, name: e.target.value })} className="min-h-10 min-w-0 flex-1 rounded-md border border-slate-300 px-2 font-bold text-[#0F2053]"/><button type="button" onClick={() => selectBaseline(scenario)} aria-pressed={comparison.baselineScenarioId === scenario.id} className="min-h-10 rounded-md border border-slate-300 px-2 text-xs font-semibold">{comparison.baselineScenarioId === scenario.id ? `✓ ${t("scenario.baseline")}` : t("scenario.baseline")}</button><button type="button" onClick={() => selectActive(scenario)} aria-pressed={comparison.activeScenarioId === scenario.id} className="min-h-10 rounded-md border border-slate-300 px-2 text-xs font-semibold">{comparison.activeScenarioId === scenario.id ? `✓ ${t("scenario.active")}` : t("scenario.active")}</button></div>
            <div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="text-xs font-semibold">{t("scenario.block")}<AppSelect value={scenario.selectedBlockId} onChange={(e) => update({ ...scenario, blockMode: "library", selectedBlockId: e.target.value as ScenarioConfiguration["selectedBlockId"] })} className="mt-1 h-10 w-full rounded-md border border-slate-300 bg-white px-2 text-sm">{blockDefinitions.map((item) => <option key={item.id} value={item.id}>{item.name} ({item.thicknessCm} cm)</option>)}</AppSelect></label><label className="text-xs font-semibold">{t("scenario.waste")}<input inputMode="decimal" value={scenario.wastePercentage} onChange={(e) => update({ ...scenario, wastePercentage: e.target.value })} className="mt-1 h-10 w-full rounded-md border border-slate-300 px-2"/></label><label className="text-xs font-semibold">{t("scenario.price")}<input inputMode="decimal" value={scenario.unitPrice} onChange={(e) => update({ ...scenario, unitPrice: e.target.value })} className="mt-1 h-10 w-full rounded-md border border-slate-300 px-2"/></label><label className="text-xs font-semibold">{t("scenario.currency")}<AppSelect value={scenario.currency} onChange={(e) => update({ ...scenario, currency: e.target.value as ScenarioConfiguration["currency"] })} className="mt-1 h-10 w-full rounded-md border border-slate-300 bg-white px-2"><option value="IQD">IQD</option><option value="USD">USD</option></AppSelect></label></div>
            {!result ? <p className="mt-3 rounded-md bg-red-50 p-2 text-sm text-red-700">{t("scenario.invalid")}</p> : <div className="mt-4 grid grid-cols-2 gap-x-3 gap-y-2 text-sm">{metrics.map(([label, read, unit]) => <div key={label} className="flex justify-between gap-2 border-b border-slate-100 py-1"><span className="text-slate-600">{t(label)}</span><span className="font-semibold tabular-nums">{formatNumber(read(result), { maximumFractionDigits: 2 })} {unit}</span></div>)}{cost ? <><div className="flex justify-between gap-2 border-b border-slate-100 py-1"><span>{t("scenario.material")}</span><strong>{formatMoney(cost.recommendedTotalCost, cost.currency)}</strong></div><div className="flex justify-between gap-2 border-b border-slate-100 py-1"><span>{t("scenario.total")}</span><strong>{formatMoney(cost.grandTotal, cost.currency)}</strong></div></> : null}</div>}
            {quantityDelta ? <p className="mt-3 text-xs font-semibold text-slate-700">{t("scenario.difference")}: {quantityDelta.absolute > 0 ? "+" : ""}{number(quantityDelta.absolute)} {t("scenario.final").toLowerCase()}</p> : null}{moneyDelta && cost ? <p className="mt-1 text-xs font-semibold text-slate-700">{t("scenario.difference")}: {moneyDelta.absolute > 0 ? "+" : ""}{formatMoney(moneyDelta.absolute, cost.currency)}</p> : null}{cost && baseline?.response.isValid && baseline.response.result.cost && baseline.response.result.cost.currency !== cost.currency ? <p className="mt-2 text-xs text-slate-500">{t("scenario.noComparableCurrency")}</p> : null}
            <label className="mt-3 block text-xs font-semibold">{t("scenario.notes")}<textarea value={scenario.notes} onChange={(e) => update({ ...scenario, notes: e.target.value })} className="mt-1 min-h-16 w-full rounded-md border border-slate-300 p-2 text-sm"/></label><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => duplicate(scenario)} className="inline-flex min-h-10 items-center gap-1 rounded-md border border-slate-300 px-2 text-xs font-semibold"><Copy size={15}/>{t("scenario.duplicate")}</button><button type="button" onClick={() => reset(scenario)} className="inline-flex min-h-10 items-center gap-1 rounded-md border border-slate-300 px-2 text-xs font-semibold"><RotateCcw size={15}/>{t("scenario.reset")}</button><button type="button" onClick={() => remove(scenario)} className="inline-flex min-h-10 items-center gap-1 rounded-md border border-red-200 px-2 text-xs font-semibold text-red-700"><Trash2 size={15}/>{t("scenario.delete")}</button></div>
          </article>; })}
      </div>
      <div className="mt-5 hidden overflow-x-auto rounded-xl border border-slate-200 lg:block"><table className="w-full min-w-[680px] text-sm"><thead><tr className="bg-slate-50"><th className="p-3 text-start">{t("scenario.title")}</th>{entries.map(({ scenario }) => <th key={scenario.id} className="p-3 text-start">{scenario.name}</th>)}</tr></thead><tbody>{metrics.map(([label, read, unit]) => <tr key={label} className="border-t border-slate-100"><th className="p-3 text-start font-medium">{t(label)}</th>{entries.map(({ scenario, response }) => <td key={scenario.id} className="p-3 tabular-nums">{response.isValid ? `${formatNumber(read(response.result), { maximumFractionDigits: 2 })} ${unit}` : "—"}</td>)}</tr>)}</tbody></table></div>
    </>}</section>;
}
